version: '3.5'
services:
  php:
    image: drupal:8-apache
    container_name: drupal-app
    depends_on:
      - mysql
    links:
      - mysql:mysql
    volumes:
      - ./www/modules:/var/www/html/modules
      - ./www/themes:/var/www/html/themes
      - ./www/profiles:/var/www/html/profiles
      - ./www/sites/default:/var/www/html/sites/default
    environment:
      - VIRTUAL_HOST=drupal.breezemakes.com
  mysql:
    image: mariadb
    container_name: drupal-mysql
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: root
      MYSQL_PASSWORD: Mko0nji9
      MYSQL_ROOT_PASSWORD: Mko0nji9
networks:
  default:
    external: 
      name: nginx-proxy-network