version: '3.5'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    privileged: false
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./log:/var/log/nginx
      - ./certs:/etc/nginx/certs
      - ./config/custom.conf:/etc/nginx/conf.d/custom.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
networks:
  default:
    name: nginx-proxy-network