version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: october-nginx
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - apache
    environment:
      - VIRTUAL_HOST=october.breezemakes.com
  apache:
    image: dragontek/octobercms:7.1-apache
    container_name: october-apache
    hostname: apache
    depends_on:
      - mysql
      - memcached
      - redis
    links:
      - mysql
      - redis
      - memcached
    environment:
      - GIT_HOSTS=gitlab.com
      - GIT_THEMES=https://github.com/rangrage/oc-mdbLoaded-theme.git
      - OCTOBER_CMS_ACTIVE_THEME=demo
      - OCTOBER_PLUGINS=RainLab.Pages;RainLab.Blog;
      - OCTOBER_DB_DRIVER=mysql
      - OCTOBER_DB_HOST=mysql
      - OCTOBER_DB_PASSWORD=Mko0nji9
      - OCTOBER_CACHE_DEFAULT=file
      - OCTOBER_SESSION_DRIVER=file
      - HOSTNAME=apache
    volumes:
      - ./.env:/var/www/html/.env
      - ./config/docker:/var/www/html/config/docker
      - ./plugins:/var/www/html/plugins
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
      - ./themes:/var/www/html/themes
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
  mysql:
    image: "mariadb"
    container_name: october-mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Mko0nji9
      - MYSQL_DATABASE=october
    volumes:
      - ./db:/var/lib/mysql
  memcached:
    image: "memcached"
    container_name: october-memcached
  redis:
    image: "redis"
    container_name: october-redis
networks:
  default:
    external: 
      name: nginx-proxy-network