version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: jenkins-nginx
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - 'jenkins:jenkins'
    environment:
      - VIRTUAL_HOST=jenkins.breezemakes.com
  jenkins:
    image: jenkins
    container_name: jenkins
    hostname: jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - ./home:/var/jenkins_home
      - ./log:/var/log/jenkins
networks:
  default:
    external: 
      name: nginx-proxy-network